#!/usr/bin/env bash

set -eo pipefail

name=$1

if [[ -z "$name" ]]; then
  >&2 echo "Usage: npm run new-package [name]"
  exit 1
fi

npx lerna create @actions/$name
cp packages/core/tsconfig.json packages/$name/tsconfig.json


namespace Drupal\my_module;

use Drupal\Core\DependencyInjection\ContainerBuilder;
use Drupal\Core\DependencyInjection\ServiceProviderBase;
use Drupal\my_module\Compiler\MyCustomExtensionPass;

class MyModuleServiceProvider extends ServiceProviderBase {

  /**
   * {@inheritdoc}
   */
  public function register(ContainerBuilder $container) {
    $container->addCompilerPass(new MyCustomExtensionPass());
  }

}
