{
  "name": "setup-node",
  "version": "3.4.1",
  "private": true,
  "description": "setup node action",
  "main": "lib/setup-node.js",
  "scripts": {
    "build": "ncc build -o dist/setup src/setup-node.ts && ncc build -o dist/cache-save src/cache-save.ts",
    "format": "prettier --no-error-on-unmatched-pattern --config ./.prettierrc.js --write \"**/*.{ts,yml,yaml}\"",
    "format-check": "prettier --no-error-on-unmatched-pattern --config ./.prettierrc.js --check \"**/*.{ts,yml,yaml}\"",
    "lint": "eslint --config ./.eslintrc.js \"**/*.ts\"",
    "lint:fix": "eslint --config ./.eslintrc.js \"**/*.ts\" --fix",
    "test": "jest --coverage",
    "pre-checkin": "npm run format && npm run lint:fix && npm run build && npm test"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/actions/setup-node.git"
  },
  "keywords": [
    "actions",
    "node",
    "setup"
  ],
  "author": "GitHub",
  "license": "MIT",
  "dependencies": {
    "@actions/cache": "^3.0.4",
    "@actions/core": "^1.10.0",
    "@actions/exec": "^1.1.0",
    "@actions/github": "^6.0.0",
    "@actions/glob": "^0.2.0",
    "@actions/http-client": "^1.0.11",
    "@actions/io": "^1.1.3",
    "@actions/tool-cache": "^1.5.4",
    "semver": "^7.5.4",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@types/jest": "^27.0.2",
    "@types/node": "^20.8.7",
    "@types/semver": "^7.5.4",
    "@types/uuid": "^9.0.3",
    "@typescript-eslint/eslint-plugin": "^5.54.0",
    "@typescript-eslint/parser": "^5.62.0",
    "@vercel/ncc": "^0.33.4",
    "eslint": "^8.52.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-jest": "^27.4.3",
    "eslint-plugin-node": "^11.1.0",
    "jest": "^27.2.5",
    "jest-circus": "^27.2.5",
    "jest-each": "^29.7.0",
    "prettier": "^3.0.3",
    "ts-jest": "^27.0.5",
    "typescript": "^4.2.3"
  },
    "name": "Publish to GitHub Package Registry"
   build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com/
        node-version: 14.x
        scope: '@dalenguyen'
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test      
    - name: publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        npm run deploy
- name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install bats
      run: git clone --depth 1 https://github.com/sstephenson/bats.git
    - name: Run tests
      run: PATH="./bats/bin:$PATH" script/test
    - name: Verify download URL checksums
      if: github.event_name == 'pull_request'
      run: ./script/mirror verify "$COMMIT_RANGE"
      env:
        COMMIT_RANGE: ${{ github.event.pull_request.base.sha }}..
        
