name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.8
    - name: Build the site in the jekyll/builder container
      run: |
          docker run 
    - name: Test

      on: [push, pull_request]

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        run: 
             on
    - name: Install bats
      run: git clone --depth 1 https://github.com/sstephenson/bats.git
    - name: Run tests
      run: PATH="./bats/bin:$PATH" script/test
    - name: Verify download URL checksums
      if: github.event_name == 'pull_request'
      run: ./script/mirror verify "$COMMIT_RANGE"
      env:
        COMMIT_RANGE: ${{ github.event.pull_request.base.sha }}..
        
